### ISSUE TITLE
Refactor getting logger

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/metakb#220]
Change this:
```
logger = logging.getLogger('metakb.cli')
logger.setLevel(logging.DEBUG)
```

to 

```
logger = logging.getLogger(__name__)
```

**Comment by jsstevenson** [comment]
In #344 I'm defining some logging from the perspective of desired CLI commands, i.e. for data management. But we should use this issue to solidly define an entry point for starting service in order to retain the beanstalk-specific logging that we like (ie dialing down a lot of the boto/etc debug statements) without introducing it in cases where metakb is being imported as a library.

**Comment by jsstevenson** [comment]
Oh, did this in #346
