### ISSUE TITLE
Add readthedocs

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/metakb#308]
This would be helpful for newcomers

**Comment by jsstevenson** [comment]
It'd be great to talk to @ahwagner at some point about how deployment works -- and maybe get us authorized on the [existing RTD instance](https://docs.cancervariants.org/en/latest/) -- because I'm fairly certain that it is currently attempting to auto-deploy there every time we merge to main, or something to that effect (see https://readthedocs.org/projects/vicc-metakb/builds/)

**Comment by korikuzma** [comment]
@jsstevenson can we close this or is there still more work that needs to be done?

**Comment by jsstevenson** [comment]
I guess fine to close? there's a lot more to write but we can tackle on an ad hoc basis
